project_id = "cbonwagnnrrpvpemaiek"

[auth]
enabled = true
site_url = "https://app.upraizen.com/"
additional_redirect_urls = [
  "https://5a2b9375-7a46-4fab-ab7c-1f802e5154ce.lovableproject.com/**",
  "https://esp-check-pro.lovable.app/**",
  "https://id-preview--5a2b9375-7a46-4fab-ab7c-1f802e5154ce.lovable.app/**",
  "https://preview--esp-check-pro.lovable.app/**",
  "https://esp-check-pro-git-*.vercel.app/*",
  "http://localhost:4176/"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10
[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true
[auth.mfa.phone]
enroll_enabled = false
verify_enabled = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6
otp_expiry = 86400
