// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmhlsouvemmzhxhsslfm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtaGxzb3V2ZW1temh4aHNzbGZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTI0MDYsImV4cCI6MjA2OTcyODQwNn0.BKkrk42PdPobpfg3uBWoWl-0yJ2bI_9hGtNIyi1C4Rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});