// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbonwagnnrrpvpemaiek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNib253YWdubnJycHZwZW1haWVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NjkyNDcsImV4cCI6MjA3MTA0NTI0N30.DdSNBNPEhzkUJWZojSLX_lnlIjeZ8qPzjNiq6oEaE08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});